// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OzkFireTakibiClient.Src.Data;

#nullable disable

namespace OzkFireTakibiClient.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260821124811_UseExcelColumnNamesForReportRows")]
    partial class UseExcelColumnNamesForReportRows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ReportImportEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorySummaryRowCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("GeneralRowCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductSummaryRowCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReportPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreCategoryRowCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreProductRowCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreSummaryRowCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRowCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .IsUnique();

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("ReportPeriodId", "PeriodType", "IsActive")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = 1");

                    b.ToTable("report_imports", (string)null);
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ReportPeriodEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "EndDate")
                        .IsUnique();

                    b.ToTable("report_periods", (string)null);
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ReportRowEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternativeName")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT")
                        .HasColumnName("Alternatif İsim");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("Kategori Kodu");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Kategori İsmi");

                    b.Property<double?>("CategoryProfitRate")
                        .HasColumnType("REAL")
                        .HasColumnName("Kategori Kar Oran");

                    b.Property<double?>("CategoryWasteRate")
                        .HasColumnType("REAL")
                        .HasColumnName("Kategori Fire Oran");

                    b.Property<double?>("ClosingAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("Dönem Sonu Tutar");

                    b.Property<double?>("ClosingQuantity")
                        .HasColumnType("REAL")
                        .HasColumnName("Dönem Sonu Miktar");

                    b.Property<double?>("CompanyPurchaseAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("Firma Alış Tutar");

                    b.Property<double?>("CompanyPurchaseQuantity")
                        .HasColumnType("REAL")
                        .HasColumnName("Firma Alış Miktar");

                    b.Property<string>("CostGroupCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Maliyet Grup Kodu");

                    b.Property<string>("CostGroupType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Maliyet Grup Tipi");

                    b.Property<double?>("CostOfSales")
                        .HasColumnType("REAL")
                        .HasColumnName("Satış Maliyeti");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OpeningAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("Dönem Başı Tutar");

                    b.Property<double?>("OpeningQuantity")
                        .HasColumnType("REAL")
                        .HasColumnName("Dönem Başı Miktar");

                    b.Property<double?>("ProfitAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("Kar Tutar");

                    b.Property<double?>("ProfitRate")
                        .HasColumnType("REAL")
                        .HasColumnName("Kar Oran");

                    b.Property<double?>("PurchaseGroupValueFactor")
                        .HasColumnType("REAL")
                        .HasColumnName("Satın Alma Grubu Değer Çarpanı");

                    b.Property<double?>("PurchaseStockValueFactor")
                        .HasColumnType("REAL")
                        .HasColumnName("Satın Alma Stok Değer Çarpanı");

                    b.Property<long>("ReportImportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RowType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceReportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rpr_id");

                    b.Property<string>("SourceReportType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("rpr_tip");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StockCode")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("Stok Kodu");

                    b.Property<string>("StockName")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT")
                        .HasColumnName("Stok İsmi");

                    b.Property<string>("StoreName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("Depo Adı");

                    b.Property<int?>("StoreNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Depo No");

                    b.Property<double?>("StoreSalesAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("Mağaza Satış Tutar");

                    b.Property<double?>("StoreSalesQuantity")
                        .HasColumnType("REAL")
                        .HasColumnName("Mağaza Satış Miktar");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("WarehouseTransferInAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("Depo Sevk Alış Tutar");

                    b.Property<double?>("WarehouseTransferInQuantity")
                        .HasColumnType("REAL")
                        .HasColumnName("Depo Sevk Alış Miktar");

                    b.Property<double?>("WarehouseTransferOutAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("Depo Sevk Satış Tutar");

                    b.Property<double?>("WarehouseTransferOutQuantity")
                        .HasColumnType("REAL")
                        .HasColumnName("Depo Sevk Satış Miktar");

                    b.Property<double?>("WasteAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("Fire Tutarı");

                    b.Property<double?>("WasteQuantity")
                        .HasColumnType("REAL")
                        .HasColumnName("Fire Miktarı");

                    b.Property<double?>("WasteRate")
                        .HasColumnType("REAL")
                        .HasColumnName("Fire Oranı");

                    b.HasKey("Id");

                    b.HasIndex("ReportImportId", "CategoryCode");

                    b.HasIndex("ReportImportId", "RowType");

                    b.HasIndex("ReportImportId", "SourceRowNumber")
                        .IsUnique();

                    b.HasIndex("ReportImportId", "StockCode");

                    b.HasIndex("ReportImportId", "StoreNumber");

                    b.ToTable("report_rows", (string)null);
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@ozkfiretakibi.local",
                            IsDeleted = false,
                            Name = "System Admin",
                            Password = "admin123",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@ozkfiretakibi.local",
                            IsDeleted = false,
                            Name = "Normal User",
                            Password = "user123",
                            Role = "User",
                            UpdatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ReportImportEntity", b =>
                {
                    b.HasOne("OzkFireTakibiClient.Src.Data.Entities.ReportPeriodEntity", "ReportPeriod")
                        .WithMany("Imports")
                        .HasForeignKey("ReportPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OzkFireTakibiClient.Src.Data.Entities.UserEntity", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportPeriod");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ReportRowEntity", b =>
                {
                    b.HasOne("OzkFireTakibiClient.Src.Data.Entities.ReportImportEntity", "ReportImport")
                        .WithMany("Rows")
                        .HasForeignKey("ReportImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportImport");
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ReportImportEntity", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ReportPeriodEntity", b =>
                {
                    b.Navigation("Imports");
                });
#pragma warning restore 612, 618
        }
    }
}
