// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OzkFireTakibiClient.Src.Data;

#nullable disable

namespace OzkFireTakibiClient.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825083928_RemoveReportScopeAddCategorySignature")]
    partial class RemoveReportScopeAddCategorySignature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ExcuseEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("ExcuseRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ReasonType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExcuseRequestId", "CreatedAt");

                    b.ToTable("excuse_entries", (string)null);
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ExcuseRequestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ReportRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StatusBeforeSuperseded")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long?>("SupersededByReportImportId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("ThresholdRate")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReportRowId")
                        .IsUnique();

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("excuse_requests", (string)null);
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ReportImportEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CategorySummaryRowCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("GeneralRowCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProductSummaryRowCount")
                        .HasColumnType("int");

                    b.Property<long>("ReportPeriodId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("StoreCategoryRowCount")
                        .HasColumnType("int");

                    b.Property<int>("StoreProductRowCount")
                        .HasColumnType("int");

                    b.Property<int>("StoreSummaryRowCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalRowCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .IsUnique();

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("ReportPeriodId", "PeriodType", "IsActive")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = 1");

                    b.ToTable("report_imports", (string)null);
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ReportPeriodEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategorySignature")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategorySignature", "EndDate")
                        .IsUnique();

                    b.ToTable("report_periods", (string)null);
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ReportRowEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AlternativeName")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("Alternatif İsim");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("Kategori Kodu");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Kategori İsmi");

                    b.Property<decimal?>("CategoryProfitRate")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Kategori Kar Oran");

                    b.Property<decimal?>("CategoryWasteRate")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Kategori Fire Oran");

                    b.Property<decimal?>("ClosingAmount")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Dönem Sonu Tutar");

                    b.Property<decimal?>("ClosingQuantity")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Dönem Sonu Miktar");

                    b.Property<decimal?>("CompanyPurchaseAmount")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Firma Alış Tutar");

                    b.Property<decimal?>("CompanyPurchaseQuantity")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Firma Alış Miktar");

                    b.Property<string>("CostGroupCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Maliyet Grup Kodu");

                    b.Property<string>("CostGroupType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Maliyet Grup Tipi");

                    b.Property<decimal?>("CostOfSales")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Satış Maliyeti");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OpeningAmount")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Dönem Başı Tutar");

                    b.Property<decimal?>("OpeningQuantity")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Dönem Başı Miktar");

                    b.Property<decimal?>("ProfitAmount")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Kar Tutar");

                    b.Property<decimal?>("ProfitRate")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Kar Oran");

                    b.Property<decimal?>("PurchaseGroupValueFactor")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Satın Alma Grubu Değer Çarpanı");

                    b.Property<decimal?>("PurchaseStockValueFactor")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Satın Alma Stok Değer Çarpanı");

                    b.Property<long>("ReportImportId")
                        .HasColumnType("bigint");

                    b.Property<string>("RowType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SourceReportId")
                        .HasColumnType("int")
                        .HasColumnName("rpr_id");

                    b.Property<string>("SourceReportType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("rpr_tip");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("StockCode")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Stok Kodu");

                    b.Property<string>("StockName")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("Stok İsmi");

                    b.Property<string>("StoreName")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("Depo Adı");

                    b.Property<int?>("StoreNumber")
                        .HasColumnType("int")
                        .HasColumnName("Depo No");

                    b.Property<decimal?>("StoreSalesAmount")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Mağaza Satış Tutar");

                    b.Property<decimal?>("StoreSalesQuantity")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Mağaza Satış Miktar");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("WarehouseTransferInAmount")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Depo Sevk Alış Tutar");

                    b.Property<decimal?>("WarehouseTransferInQuantity")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Depo Sevk Alış Miktar");

                    b.Property<decimal?>("WarehouseTransferOutAmount")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Depo Sevk Satış Tutar");

                    b.Property<decimal?>("WarehouseTransferOutQuantity")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Depo Sevk Satış Miktar");

                    b.Property<decimal?>("WasteAmount")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Fire Tutarı");

                    b.Property<decimal?>("WasteQuantity")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Fire Miktarı");

                    b.Property<decimal?>("WasteRate")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)")
                        .HasColumnName("Fire Oranı");

                    b.HasKey("Id");

                    b.HasIndex("ReportImportId", "CategoryCode");

                    b.HasIndex("ReportImportId", "RowType");

                    b.HasIndex("ReportImportId", "SourceRowNumber")
                        .IsUnique();

                    b.HasIndex("ReportImportId", "StockCode");

                    b.HasIndex("ReportImportId", "StoreNumber");

                    b.HasIndex("StoreNumber", "RowType");

                    b.ToTable("report_rows", (string)null);
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.StoreEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExcuseEligible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StoreNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StoreNumber");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@ozkfiretakibi.local",
                            IsDeleted = false,
                            Name = "System Admin",
                            Password = "admin123",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@ozkfiretakibi.local",
                            IsDeleted = false,
                            Name = "Normal User",
                            Password = "user123",
                            Role = "User",
                            UpdatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ExcuseEntryEntity", b =>
                {
                    b.HasOne("OzkFireTakibiClient.Src.Data.Entities.UserEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OzkFireTakibiClient.Src.Data.Entities.ExcuseRequestEntity", "ExcuseRequest")
                        .WithMany("Entries")
                        .HasForeignKey("ExcuseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ExcuseRequest");
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ExcuseRequestEntity", b =>
                {
                    b.HasOne("OzkFireTakibiClient.Src.Data.Entities.ReportRowEntity", "ReportRow")
                        .WithOne("ExcuseRequest")
                        .HasForeignKey("OzkFireTakibiClient.Src.Data.Entities.ExcuseRequestEntity", "ReportRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OzkFireTakibiClient.Src.Data.Entities.UserEntity", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReportRow");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ReportImportEntity", b =>
                {
                    b.HasOne("OzkFireTakibiClient.Src.Data.Entities.ReportPeriodEntity", "ReportPeriod")
                        .WithMany("Imports")
                        .HasForeignKey("ReportPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OzkFireTakibiClient.Src.Data.Entities.UserEntity", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportPeriod");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ReportRowEntity", b =>
                {
                    b.HasOne("OzkFireTakibiClient.Src.Data.Entities.ReportImportEntity", "ReportImport")
                        .WithMany("Rows")
                        .HasForeignKey("ReportImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportImport");
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ExcuseRequestEntity", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ReportImportEntity", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ReportPeriodEntity", b =>
                {
                    b.Navigation("Imports");
                });

            modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.ReportRowEntity", b =>
                {
                    b.Navigation("ExcuseRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
