// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OzkFireTakibiClient.Src.Data;

#nullable disable

namespace OzkFireTakibiClient.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260820132752_SeedInitialUsers")]
partial class SeedInitialUsers
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

        modelBuilder.Entity("OzkFireTakibiClient.Src.Data.Entities.UserEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Role")
                    .HasColumnType("TEXT");

                b.Property<string>("StoreName")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("users");

                b.HasData(
                    new
                    {
                        Id = 1,
                        CreatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                        Email = "admin@ozkfiretakibi.local",
                        IsDeleted = false,
                        Name = "System Admin",
                        Password = "admin123",
                        Role = "Admin",
                        UpdatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                    },
                    new
                    {
                        Id = 2,
                        CreatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                        Email = "user@ozkfiretakibi.local",
                        IsDeleted = false,
                        Name = "Normal User",
                        Password = "user123",
                        Role = "User",
                        UpdatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                    });
            });
#pragma warning restore 612, 618
    }
}
